name: build
on: [push, pull_request]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: |
        docker compose up -d
        go test -mod=vendor -covermode=count ./app/... -coverprofile $GITHUB_WORKSPACE/cover.out

    - name: install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.49.0

    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./...

    - name: Submit coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

    - name: build and push branched image
      if: github.event_name == 'push'
      run: |
        docker build -t adobromilskiy/quake3-logcatcher:${{ github.ref_name }} .
        docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWD }}
        docker push adobromilskiy/quake3-logcatcher:${{ github.ref_name }}

    - name: build and push tagged image
      if: github.event_name == 'push' && github.event.ref_type == 'tag'
      run: |
        GIT_TAG="${GITHUB_REF#refs/tags/}"
        docker build -t adobromilskiy/quake3-logcatcher:${GIT_TAG} .
        docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWD }}
        docker push adobromilskiy/quake3-logcatcher:${GIT_TAG}
        docker tag adobromilskiy/quake3-logcatcher:${GIT_TAG} adobromilskiy/quake3-logcatcher:latest
        docker push adobromilskiy/quake3-logcatcher:latest