name: build
on: [push, pull_request]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: |
        docker compose up -d
        go test -mod=vendor -covermode=count ./app/... -coverprofile $GITHUB_WORKSPACE/cover.out

    - name: install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.49.0

    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./...

    - name: Submit coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: build and push branched image
      if: github.event_name == 'push' && github.ref != 'refs/heads/main'
      env:
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo ${DOCKERHUB_PASSWD} | docker login --username ${USERNAME} --password-stdin
        echo ${GITPKG_TOKEN} | docker login ghcr.io --username ${USERNAME} --password-stdin
        docker buildx build --push --platform linux/amd64,linux/arm64 \
          -t ${USERNAME}/quake3-logcatcher:${{ github.ref_name }} \
          -t ghcr.io/${USERNAME}/quake3-logcatcher:${{ github.ref_name }} .

    - name: build and push latest image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo ${DOCKERHUB_PASSWD} | docker login --username ${USERNAME} --password-stdin
        echo ${GITPKG_TOKEN} | docker login ghcr.io --username ${USERNAME} --password-stdin
        docker buildx build --push --platform linux/amd64,linux/arm64 \
          -t ${USERNAME}/quake3-logcatcher:latest \
          -t ghcr.io/${USERNAME}/quake3-logcatcher:latest .

    - name: build and push tagged image
      if: github.event_name == 'push' && github.event.ref_type == 'tag'
      env:
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        GIT_TAG="${GITHUB_REF#refs/tags/}"
        echo ${DOCKERHUB_PASSWD} | docker login --username ${USERNAME} --password-stdin
        echo ${GITPKG_TOKEN} | docker login ghcr.io --username ${USERNAME} --password-stdin
        docker buildx build --push --platform linux/amd64,linux/arm64 \
          -t ${USERNAME}/quake3-logcatcher:${GIT_TAG} \
          -t ghcr.io/${USERNAME}/quake3-logcatcher:${GIT_TAG} .